Add testing for Django 2.1 (#127)
* Fix compatibility with pip 10+

* Fix Travis build failure on MacOS

Error: python 2.7.14 is already installed
To upgrade to 3.6.5, run `brew upgrade python`

* Add testing for Django 2.1